// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Home = require("./Home.js");
var Detail = require("./Detail.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var StackNavigator$BsReactNavigation = require("bs-react-navigation/lib/js/src/StackNavigator.js");

var navigationConfig = {
  initialRouteName: "Detail"
};

var reactClass = StackNavigator$BsReactNavigation.create(/* :: */[
      /* tuple */[
        "Home",
        {
          screen: (function () {
              return ReasonReact.element(undefined, undefined, Home.make(/* array */[]));
            })
        }
      ],
      /* :: */[
        /* tuple */[
          "Detail",
          {
            screen: (function () {
                return ReasonReact.element(undefined, undefined, Detail.make(/* array */[]));
              })
          }
        ],
        /* [] */0
      ]
    ], navigationConfig);

exports.navigationConfig = navigationConfig;
exports.reactClass = reactClass;
/* reactClass Not a pure module */
