// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Home = require("./Home.js");
var Details = require("./Details.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var StackNavigator$BsReactNavigation = require("bs-react-navigation/lib/js/src/StackNavigator.js");

function mapRoute(r) {
  if (r) {
    return /* tuple */[
            "Details",
            /* record */[/* screen */ReasonReact.wrapReasonForJs(Details.component, Details.make)]
          ];
  } else {
    return /* tuple */[
            "Home",
            /* record */[/* screen */ReasonReact.wrapReasonForJs(Home.component, Home.make)]
          ];
  }
}

var Config_000 = /* routes : :: */[
  /* Home */0,
  /* :: */[
    /* Details */["params"],
    /* [] */0
  ]
];

var Config = /* module */[
  Config_000,
  /* mapRoute */mapRoute
];

var include = StackNavigator$BsReactNavigation.CreateStackNavigator(Config);

var StackNavigator = include[0];

var reactClass = StackNavigator[/* navigatorComponent */0];

exports.Config = Config;
exports.StackNavigator = StackNavigator;
exports.reactClass = reactClass;
/* include Not a pure module */
