// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var cs = {
  p: 1,
  s: (function (cn, p) {
      return /* record */[
              /* nn */cn,
              /* pp */p
            ];
    })
};

function g(a) {
  if (typeof a === "number") {
    return {
            p: 1,
            s: (function (cn, p) {
                return /* record */[
                        /* nn */cn,
                        /* pp */p
                      ];
              })
          };
  } else if (a[0] >= 67) {
    return {
            p: 1,
            s: (function (cn, p) {
                return /* record */[
                        /* nn */cn,
                        /* pp */p
                      ];
              })
          };
  } else {
    return {
            p: 1,
            s: (function (cn, p) {
                return /* record */[
                        /* nn */cn,
                        /* pp */p
                      ];
              })
          };
  }
}

exports.cs = cs;
exports.g = g;
/* No side effect */
