// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Stack$BsReactNavigation = require("bs-react-navigation/lib/js/src/Stack.js");

var Config = /* module */[/* routes : :: */[
    /* Home */0,
    /* :: */[
      /* Details */1,
      /* [] */0
    ]
  ]];

var include = Stack$BsReactNavigation.Make(Config);

var Navigation = include[0];

var NavigationOptions = include[1];

var Navigator = include[2];

exports.Config = Config;
exports.Navigation = Navigation;
exports.NavigationOptions = NavigationOptions;
exports.Navigator = Navigator;
/* include Not a pure module */
