// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Stack$BsReactNavigation = require("bs-react-navigation/lib/js/src/Stack.js");

var Config = /* module */[/* routes : :: */[
    /* Home */0,
    /* :: */[
      /* Details */1,
      /* [] */0
    ]
  ]];

var include = Stack$BsReactNavigation.Make(Config);

var Navigator = include[0];

exports.Config = Config;
exports.Navigator = Navigator;
/* include Not a pure module */
