// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function greeting(name) {
  return "Welcome to " + (name + " !!!");
}

exports.greeting = greeting;
/* No side effect */
