// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var createStackNavigator = (
  function(componment, second){
    const React = require('react');
    const RNav = require('react-navigation');

    const RootStack = RNav.createStackNavigator({
      1: {
        screen: componment
      },
      0: {
        screen: second
      }
    },
    {
      initialRouteName: "0",
    }
    );

    return class App extends React.Component {
      render() {
        return <RootStack />;
      }
    }
  }
);

exports.createStackNavigator = createStackNavigator;
/* createStackNavigator Not a pure module */
