// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var ReactNavigation = require("react-navigation");

function create(routes, navigatorConfig) {
  var jsRoutes = Js_dict.fromList(routes);
  return ReactNavigation.createStackNavigator(jsRoutes, navigatorConfig);
}

exports.create = create;
/* Js_dict Not a pure module */
