// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");

function Configure(Config) {
  var Navigation = /* module */[];
  var make = function (getScreen) {
    console.log(Config[/* routes */0]);
    List.map((function (route) {
            var component = Curry._1(getScreen, route);
            console.log(component);
            return /* () */0;
          }), Config[/* routes */0]);
    return 1;
  };
  return /* module */[
          /* Navigation */Navigation,
          /* make */make
        ];
}

exports.Configure = Configure;
/* No side effect */
