// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");

function CreateStackNavigator(Config) {
  var generateJsStackNavigatorConfig = Js_dict.fromList(List.map(Config[/* mapRoute */1], Config[/* routes */0]));
  console.log(generateJsStackNavigatorConfig);
  var StackNavigator = /* module */[/* generateJsStackNavigatorConfig */generateJsStackNavigatorConfig];
  return /* module */[/* StackNavigator */StackNavigator];
}

exports.CreateStackNavigator = CreateStackNavigator;
/* Js_dict Not a pure module */
