// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var ReactNavigation = require("react-navigation");

function Make(Config) {
  var NavigationProp = /* module */[];
  var NavigationOptions = /* module */[];
  var configureRouteToJs = function (param) {
    return {
            screen: param[/* screen */0]
          };
  };
  var configureRouteFromJs = function (param) {
    return /* record */[/* screen */param.screen];
  };
  var configure = function (mapRoute, initial) {
    var routes = Js_dict.fromList(List.map((function (route) {
                var match = Curry._1(mapRoute, route);
                return /* tuple */[
                        match[0],
                        configureRouteToJs(match[1])
                      ];
              }), Config[/* routes */0]));
    var match = Curry._1(mapRoute, initial);
    return ReactNavigation.createStackNavigator(routes, {
                initialRouteName: match[0]
              });
  };
  var Navigator = /* module */[
    /* configureRouteToJs */configureRouteToJs,
    /* configureRouteFromJs */configureRouteFromJs,
    /* configure */configure
  ];
  return /* module */[
          /* NavigationProp */NavigationProp,
          /* NavigationOptions */NavigationOptions,
          /* Navigator */Navigator
        ];
}

exports.Make = Make;
/* Js_dict Not a pure module */
