// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNavigation = require("react-navigation");

function routeConfigurationToJs(param) {
  return {
          screen: param[/* screen */0]
        };
}

function navigatorConfigToJs(param) {
  return {
          initialRouteName: param[/* initialRouteName */0]
        };
}

function CreateStackNavigator(funarg) {
  var routes = Js_dict.fromList(List.map((function (route) {
              var match = Curry._1(funarg[/* mapRoute */2], route);
              var configuration = match[1];
              var withNavigation = function (navigation) {
                return ReasonReact.element(undefined, undefined, Curry._2(configuration[/* screen */0], navigation, /* array */[]));
              };
              return /* tuple */[
                      match[0],
                      routeConfigurationToJs(/* record */[/* screen */withNavigation])
                    ];
            }), funarg[/* routes */1]));
  var match = Curry._1(funarg[/* mapRoute */2], funarg[/* navigatorConfig */0][/* initialRouteName */0]);
  var sConfig = navigatorConfigToJs(/* record */[/* initialRouteName */match[0]]);
  var $$navigator = ReactNavigation.createStackNavigator(routes, sConfig);
  return [[$$navigator]];
}

exports.CreateStackNavigator = CreateStackNavigator;
/* Js_dict Not a pure module */
